# Generated by Django 4.2.5 on 2023-09-18 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='L', max_length=1)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
