# Generated by Django 4.2.5 on 2023-09-18 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='concluido',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='creation',
            new_name='criado',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='expiracao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('A', 'Alta'), ('M', 'Média')], default='B', max_length=1),
        ),
    ]
