# Generated by Django 4.2.5 on 2023-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_rename_done_todo_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prioridade',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baixa'), ('M', 'Média')], default='B', max_length=1),
        ),
    ]
