# Generated by Django 4.2.5 on 2023-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todo_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='prioridade',
            field=models.CharField(choices=[('M', 'Média'), ('A', 'Alta'), ('B', 'Baixa')], default='B', max_length=1),
        ),
    ]
